# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170714_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wait',
            field=models.BooleanField(default=False),
        ),
    ]
