# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170714_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'programming'), ('b', 'personal'), ('c', 'Brain storming')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
