# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170714_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'programming'), ('b', 'personal'), ('c', 'Brain storming')], default=1, max_length=3),
        ),
    ]
